routes/web.php
<?php

use App\Http\Controllers\view\viewDetailMobilController;
use App\Http\Controllers\view\viewMobilController;
use App\Http\Controllers\view\viewTypeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::name('mobil.brand.')->prefix('/mobil/brand/')->group(function(){
    Route::get('all', [viewMobilController::class, 'index'])->name('all');
    Route::get('create', [viewMobilController::class, 'create'])->name('create');
    Route::get('edit/{id}', [viewMobilController::class, 'edit'])->name('edit');
    Route::post('make', [viewMobilController::class, 'store'])->name('make');
    Route::post('change', [viewMobilController::class, 'update'])->name('change');
    Route::get('destroy/{id}', [viewMobilController::class, 'destroy'])->name('destroy');
});

Route::name('mobil.type.')->prefix('/mobil/type')->group(function(){
    Route::get('all', [viewTypeController::class, 'index'])->name('all'); // to show all data
    Route::get('create', [viewTypeController::class, 'create'])->name('create'); // to create data
    Route::get('edit/{id}', [viewTypeController::class, 'edit'])->name('edit'); // to update data
    Route::post('make', [viewTypeController::class, 'store'])->name('make'); // storing data
    Route::post('change', [viewTypeController::class, 'update'])->name('change'); // store updated data
    Route::get('destroy/{id}', [viewTypeController::class, 'destroy'])->name('destroy'); // delete data
});

Route::name('mobil.type.')->prefix('/mobil/type/')->group(function(){
    Route::get('{id}/spac', [viewDetailMobilController::class, 'index'])->name('spec'); // to show all data
    Route::get('{id}/spec/create', [viewDetailMobilController::class, 'create'])->name('spec.create'); // to create data
    Route::get('{id}/spec/edit', [viewDetailMobilController::class, 'edit'])->name('spec.edit'); // to update data
    Route::post('spec/make', [viewDetailMobilController::class, 'store'])->name('spec.make');
});

resources/views/layout/detail/create.blade.php
@extends('page.index')
@section('section-name', 'Detail Create')
@section('content')
<form method="post" action="{{ route('mobil.type.spec.make') }}">
    @csrf
    <div class="form-group row">
        <label for="cdBrand" class="mr-2 col-md-2">Brand Select</label>
        <select name="cd_brand" id="cdBrand" class="btn btn-secondary dropdown-toggle col-md-2" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" type="button">
            <div class="dropdown-menu" aria-labelledby="cdBrand">
                <option value="">--Select Brand--</option>
                @foreach ($data as $item)
                    <option value="{{ $item->cd_brand }}" class="dropdown-item text-light">{{ $item->desc_brand }}</option>
                @endforeach
            </div>
        </select>
    </div>

    <div class="form-group row">
        <label for="cdType" class="mr-2 col-md-2">Type Select</label>
        <select name="cd_type" id="cdBrand" class="btn btn-secondary dropdown-toggle col-md-2" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" type="button">
            <div class="dropdown-menu" aria-labelledby="cdType">
                <option value="">--Select Brand--</option>
                @foreach ($data as $item)
                    <option value="{{ $item->cd_type }}" class="dropdown-item text-light">{{ $item->desc_type }}</option>
                @endforeach
            </div>
        </select>
    </div>

    <div class="form-group row">
        <label for="year" class="mr-2 col-md-2">Year</label>
        <input type="text" name="year" id="year" class="col-md-4">
    </div>
    <div class="form-group row">
        <label for="price" class="mr-2 col-md-2">Price</label>
        <input type="text" name="price" id="price" class="col-md-4">
    </div>
    <div class="form-group row">
        <label for="spec" class="mr-2 col-md-2">Specification</label>
        <input type="text" name="spec" id="spec" class="col-md-4">
    </div>

    <div class="row justify-content-start">
        {{-- <button type="submit" class="btn btn-primary btn-submit mr-2">Save</button> --}}
        <input type="submit" value="Save" class="btn btn-primary mr-2">
        <a href="{{ route('mobil.type.all') }}" class="btn btn-primary ">Back</a>
    </div>
</form>
@endsection

resources/views/layout/detail/index.blade.php
@extends('page.index')
@section('section-name', 'Details')
@section('content')

@foreach ($joinBrandType as $item)
    <a href="{{ route('mobil.type.spec.create', $item->cd_type) }}">Add Spec</a>
    <h4>Brand : <span>{{ $item->desc_brand }}</span></h4>
    <h4>Type : <span>{{ $item->desc_type }}</span></h4>
@endforeach
<table class="table">
    <thead>
      <tr>
        <th scope="col">Year</th>
        {{-- <th scope="col">Brand</th> --}}
        <th scope="col">Price</th>
        <th scope="col">Spec</th>
        <th scope="col">Photo</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($detail as $item)
        <tr>
            <td>{{ $item->year }}</td>
            <td>{{ $item->price }}</td>
            <td>{{ $item->spec }}</td>
            <td>{{ $item->photo }}</td>
            <td>
                <a href="{{ url('mobil/type/edit/'. $item->cd_type) }}" class="btn btn-warning" id="btnEdit">Edit</a>
                <a href="{{ route('mobil.type.destroy', $item->cd_type) }}" class="btn btn-danger" id="btnDelete" ">Delete</a>
            </td>
        </tr>
      @endforeach
    </tbody>
</table>
@endsection