routes/web.php
<?php

use App\Http\Controllers\view\viewDetailMobilController;
use App\Http\Controllers\view\viewMobilController;
use App\Http\Controllers\view\viewTypeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::name('mobil.brand.')->prefix('/mobil/brand/')->group(function(){
    Route::get('all', [viewMobilController::class, 'index'])->name('all');
    Route::get('create', [viewMobilController::class, 'create'])->name('create');
    Route::get('edit/{id}', [viewMobilController::class, 'edit'])->name('edit');
    Route::post('make', [viewMobilController::class, 'store'])->name('make');
    Route::post('change', [viewMobilController::class, 'update'])->name('change');
    Route::get('destroy/{id}', [viewMobilController::class, 'destroy'])->name('destroy');
});

Route::name('mobil.type.')->prefix('/mobil/type')->group(function(){
    Route::get('all', [viewTypeController::class, 'index'])->name('all'); // to show all data
    Route::get('create', [viewTypeController::class, 'create'])->name('create'); // to create data
    Route::get('edit/{id}', [viewTypeController::class, 'edit'])->name('edit'); // to update data
    Route::post('make', [viewTypeController::class, 'store'])->name('make'); // storing data
    Route::post('change', [viewTypeController::class, 'update'])->name('change'); // store updated data
    Route::get('destroy/{id}', [viewTypeController::class, 'destroy'])->name('destroy'); // delete data
});

Route::name('mobil.type.')->prefix('/mobil/type/')->group(function(){
    Route::get('{id}/spac', [viewDetailMobilController::class, 'index'])->name('spec'); // to show all data
    Route::get('{id}/spec/create', [viewDetailMobilController::class, 'create'])->name('spec.create'); // to create data
    Route::get('{id}/spec/edit', [viewDetailMobilController::class, 'edit'])->name('spec.edit'); // to update data
    Route::post('spec/make', [viewDetailMobilController::class, 'store'])->name('spec.make');
});

resources/views/layout/type/create.blade.php
@extends('page.index')
@section('section-name', 'create')
@section('content')
    <form method="post" action="{{ route('mobil.type.make') }}">
        @csrf
        <div class="form-group">
            <label for="cdBrand" class="mr-2">Brand Select</label>
            <select name="cd_brand" id="cdBrand" class="btn btn-secondary dropdown-toggle" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" type="button">
                <div class="dropdown-menu" aria-labelledby="cdBrand">
                    @foreach ($data as $item)
                        <option value="{{ $item->cd_brand }}" class="dropdown-item text-light">{{ $item->desc_brand }}</option>
                    @endforeach
                </div>
            </select>
        </div>

        <div class="form-group">
            <label for="cdType" class="mr-2">Type Code</label>
            <input type="text" name="cd_type" id="cdType">
        </div>

        <div class="form-group">
            <label for="descType" class="mr-2">Type Name</label>
            <input type="text" name="desc_type" id="descType">
        </div>

        <div class="row justify-content-start">
            {{-- <button type="submit" class="btn btn-primary btn-submit mr-2">Save</button> --}}
            <input type="submit" value="Save" class="btn btn-primary mr-2">
            <a href="{{ route('mobil.type.all') }}" class="btn btn-primary ">Back</a>
        </div>
    </form>
@endsection

resources/views/layout/type/edit.blade.php
@extends('page.index')
@section('section-name', 'Edit')
@section('content')
    <form action="{{ route('mobil.type.change') }}" method="post">
        @csrf
        @foreach ($data as $item)
            <div class="form-group">
                <label for="cdType">Type Code</label>
                <input type="text" name="cd_type" id="cdType" value="{{ $item->cd_type }}">
            </div>
            <div class="form-group">
                <label for="cdBrand">Brand Code</label>
                <input type="text" name="cd_brand" id="cdBrand" value="{{ $item->cd_brand }}">
            </div>
            <div class="form-group">
                <label for="descType">Type Name</label>
                <input type="text" name="desc_type" id="descType" value="{{ $item->desc_type }}">
            </div>
        @endforeach
        <div class="row justify-content-start">
            <input type="submit" value="save" class="btn btn-primary mr-1">
            <a href="{{ route('mobil.type.all') }}" class="btn btn-primary">Go Back</a>
        </div>
    </form>
@endsection

resources/views/layout/type/index.blade.php
@extends('page.index')
@section('section-name', 'Type')
@section('content')
<a href="{{ route('mobil.type.create') }}" class="btn btn-primary mb-3">Create Type</a>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Code Type</th>
        {{-- <th scope="col">Brand</th> --}}
        <th scope="col">Type</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($datas as $item)
        <tr>
            <td>{{ $item->cd_type }}</td>
            {{-- <td>{{ $item->desc_brand }}</td> --}}
            <td>{{ $item->desc_type }}</td>
            <td>
                <a href="{{ route('mobil.type.spec', $item->cd_type) }}" class="btn btn-primary">Detail</a>
                <a href="{{ url('mobil/type/edit/'. $item->cd_type) }}" class="btn btn-warning" id="btnEdit">Edit</a>
                <a href="{{ route('mobil.type.destroy', $item->cd_type) }}" class="btn btn-danger" id="btnDelete" ">Delete</a>
            </td>
        </tr>
      @endforeach
    </tbody>
</table>
@endsection