routes/web.php
<?php

use App\Http\Controllers\view\viewDetailMobilController;
use App\Http\Controllers\view\viewMobilController;
use App\Http\Controllers\view\viewTypeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::name('mobil.brand.')->prefix('/mobil/brand/')->group(function(){
    Route::get('all', [viewMobilController::class, 'index'])->name('all');
    Route::get('create', [viewMobilController::class, 'create'])->name('create');
    Route::get('edit/{id}', [viewMobilController::class, 'edit'])->name('edit');
    Route::post('make', [viewMobilController::class, 'store'])->name('make');
    Route::post('change', [viewMobilController::class, 'update'])->name('change');
    Route::get('destroy/{id}', [viewMobilController::class, 'destroy'])->name('destroy');
});

Route::name('mobil.type.')->prefix('/mobil/type')->group(function(){
    Route::get('all', [viewTypeController::class, 'index'])->name('all'); // to show all data
    Route::get('create', [viewTypeController::class, 'create'])->name('create'); // to create data
    Route::get('edit/{id}', [viewTypeController::class, 'edit'])->name('edit'); // to update data
    Route::post('make', [viewTypeController::class, 'store'])->name('make'); // storing data
    Route::post('change', [viewTypeController::class, 'update'])->name('change'); // store updated data
    Route::get('destroy/{id}', [viewTypeController::class, 'destroy'])->name('destroy'); // delete data
});

Route::name('mobil.type.')->prefix('/mobil/type/')->group(function(){
    Route::get('{id}/spac', [viewDetailMobilController::class, 'index'])->name('spec'); // to show all data
    Route::get('{id}/spec/create', [viewDetailMobilController::class, 'create'])->name('spec.create'); // to create data
    Route::get('{id}/spec/edit', [viewDetailMobilController::class, 'edit'])->name('spec.edit'); // to update data
    Route::post('spec/make', [viewDetailMobilController::class, 'store'])->name('spec.make');
});

app/Models/Mobil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mobil extends Model
{
    use HasFactory;
}

resources/views/layout/mobil/create.blade.php
@extends('page.index')
@section('section-name', 'Create')
@section('content')

    <ul id="saveform_errList"></ul>
    <form method="post">
        @csrf
        <div class="form-group">
            <label for="cdBrand">Code Brand</label>
            <input type="text" name="cd_brand" id="cdBrand">
        </div>
        <div class="form-group">
            <label for="descBrand">Desc Brand</label>
            <input type="text" name="desc_brand" id="descBrand">
        </div>
        <div class="row justify-content-start">
            <button type="submit" class="btn btn-primary btn-submit mr-2">Save</button>
            <a href="{{ route('mobil.brand.all') }}" class="btn btn-primary ">Back</a>
        </div>

    </form>

@endsection

@section('script')
    <script>

        $(document).ready(function () {
            $('.btn-submit').click(function (e) {
                e.preventDefault();

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    type: "post",
                    url: "{{ route('mobil.brand.make') }}",
                    data: {
                        'cd_brand': $('#cdBrand').val(),
                        'desc_brand': $('#descBrand').val(),
                    },
                    dataType: "json",
                    success: function (response) {
                        // console.log(response);
                        if(response.status == 400){
                            $('#saveform_errList').html("");
                            $('#saveform_errList').addClass('alert alert-danger');
                            $.each(response.message, function (key, err_values) {
                                $('#saveform_errList').append('<li>'+ err_values +'</li>')
                            });
                        }
                        else{
                            $('#saveform_errList').html("");
                            $('#saveform_errList').addClass('alert alert-success');
                            $('#saveform_errList').text(response.message);
                            window.location.replace("{{ route('mobil.brand.all') }}")
                        }
                    }
                });
            });
        });
    </script>
@endsection

resources/views/layout/mobil/edit.blade.php
@extends('page.index')
@section('section-name', 'Edit')
@section('content')
    <form method="post" action="{{ route('mobil.brand.change') }}">
        @csrf
        {{-- @foreach ($data as $item) --}}
        <div class="form-group">
            <label for="cdBrand">Code Brand</label>
            <input type="text" name="cd_brand" id="cdBrand" value="{{ $res['cd_brand'] }}">
            print_r($res)
        </div>
        <div class="form-group">
            <label for="descBrand">Name Brand</label>
            <input type="text" name="desc_brand" id="descBrand" value="{{ $res['desc_brand'] }}">
        </div>
        {{-- @endforeach --}}
        <button type="submit" class="btn btn-primary btn-submit">Save</button>
    </form>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            // console.log(:id);
            $('.btn-submit').click(function (e) {
                e.preventDefault();

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "post",
                    url: "{{ url('mobil/brand/change') }}",
                    data: {
                        'cd_brand': $('#cdBrand').val(),
                        'desc_brand': $('#descBrand').val(),
                    },
                    dataType: "json",
                    success: function (response) {
                        window.location.replace("{{ route('mobil.brand.all') }}")
                    }
                });
            });
        });
    </script>
@endsection

resources/views/layout/mobil/index.blade.php
@extends('page.index')
@section('section-name', 'Dashboard')
@section('content')
<a href="{{ route('mobil.brand.create') }}" class="btn btn-primary mb-3">Create Brand</a>

{{-- ======modal====== --}}
{{-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deleting Data?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <h6>Are you Sure?</h6>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </div> --}}
  {{-- ======end Modal====== --}}

<table class="table">
    <thead>
      <tr>
        <th scope="col">Code Brand</th>
        <th scope="col">Name Brand</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($collection as $item)
        <tr>
            <td>{{ $item->cd_brand }}</td>
            <td>{{ $item->desc_brand }}</td>
            <td>
                <a href="{{ url('mobil/brand/edit/'. $item->cd_brand) }}" class="btn btn-warning" id="btnEdit">Edit</a>
                <a href="{{ url('mobil/brand/destroy/'. $item->cd_brand) }}" class="btn btn-danger" id="btnDelete" ">Delete</a>
            </td>
        </tr>
      @endforeach
    </tbody>
</table>
@endsection

@section('script')
    <script>
        // $(document).ready(function () {
        //     $('#btnDelete').click(function (e) {
        //         e.preventDefault();

        //     });
        // });
    </script>
@endsection